baseurl = "https://inspiritana.org/"
languageCode = "en-en"
title = "inspiritana.org - get inspired & share the spirit!"
description = "Cale Alit, a modern nomad, yoga teacher, meditation instructor, musician, speaker & more. - Get inspired & share the spirit!"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "inspiritana"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

refLinksErrorLevel = "warning"
enableRobotsTXT = true

# Define the number of posts per page
paginate = 10
theme = "universal"

# Pluralize titles in lists using inflect
pluralizeListTitles = false
# Preserve special characters in taxonomy names ("Gérard Depardieu" vs "Gerard Depardieu")
preserveTaxonomyNames = true

[taxonomies]
    author = "author"
    category = "categories"
    featured = "featured"
    banner = "banner"
    subtitle = "subtitle"
    tags = "tags"

[params]
    author = "Cale"


    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = ""


    footer = false
    email = "kontakt@inspiritana.org"
    about_us = "Spannende Reiseberichte, inspirierende Ideen und interessante Artikel und Videos über Yoga, Gesundheit, Meditation und mehr. Kostenloser Yoga-Unterricht (auf Spendenbasis) für Einzelpersonen und Gruppen. Individuell, kreativ, einzigartig, aufregend!"
    copyright = "2020 - inspiritana.org"
    date_format = "02. 01. 2006"
    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = ""

[[params.menu]]
    name = "Home"
    url  = "/"
    weight = 1

[[params.menu]]
    name = "About me"
    url = "/about"
    weight = 2

[[params.menu]]
    name = "Yoga"
    url  = "/yoga"
    weight = 3

[[params.menu]]
    name = "Music"
    url  = "/music"
    weight = 4

[[params.menu]]
    name = "Contact"
    url  = "/contact"
    weight = 5

[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:your@email.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"


# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = false
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

#Teaser-Box für YogaInSpirit
[params.see_more]
    enable = true
    title = "Lust auf Yoga?"
    subtitle = "Mit dem #YogaInSpirit-Projekt möchte ich die wundervolle Philosophie & Praxis des Yogas jedem zugänglich machen - deshalb unterrichte ich ausschließlich kostenlos bzw. auf Spendenbasis."
    subsubtitle = "#YogaInSpirit - because yoga is not a business, it's a passion."
    link_url = "#"
    link_text = "Erfahre mehr"

[params.recent_posts]
    enable = true
    title = "Aus unserem Blog"
    subtitle = ""

[params.featuredposts]
    enable = true
    title = "Blog"
    subtitle = ""

[params.connect]

    
    [[params.connect.list]]
        name= "Instagram"
        icon= "instagram"
        link= "https://instagram.com/inspiritana/"

    [[params.connect.list]]
        name = "Facebook"
        icon = "facebook-square"
        link= "http://facebook.com/inspiritana.org"

    [[params.connect.list]]
        name = "YouTube"
        icon = "youtube-square"
        link = "https://www.youtube.com/inspiritana"
        
    [[params.connect.list]]
        name= "E-Mail"
        icon= "envelope-square"
        #link wird manuell in partials/connect.html festgelegt (Spam-Schutz)
        link= ""


# privacy settings for GDPR (more in hugo docs)
[privacy.youtube]
    disable = false
    privacyEnhanced = true



ignoreFiles = [ ".foo", ".ign" ]